version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check the npm registry for updates every day at 10:15 (weekdays)
    schedule:
      interval: "daily"
    # assignees lennart & david to the pr
    assignees:
      - "l3nnartt"
      - "DqvidTM"
    # pr requests limit
    open-pull-requests-limit: 100
